# Generated by Django 3.2 on 2021-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210512_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
